# http://www.appveyor.com/docs/appveyor-yml

branches:
  only:
    - develop
    - main

environment:
  # bad, but without this, gitversion doesn't work anymore
  IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1
  azure-key-vault-url:
    secure: 1mKS/HfCVq+iYNRVSrrN8NEowOkKt3knrpMzw+SOy3g=
  azure-key-vault-client-id:
    secure: JfSqzmsJdXB6uIxttCRoQw1NygwxqXHDj9uIqQnWOb9VCnQYlRPlAnxgW0yTSX4b
  azure-key-vault-tenant-id:
    secure: FxjkcqtpulfpDpfSAu4onaLVP/H1S1ORRCQCqsZkDC6YhCSmFoMxYNsWv5uGe3ah
  azure-key-vault-client-secret:
    secure: CUpRJxMLeUZwNPMcqI0wECaWfy5AMnWn1UZhBd9WnQ3Z16lJP1Vzrkf24mccbhUD
  azure-key-vault-certificate:
    secure: BSPdW2TgnQtoQXXbeDECug==

skip_tags: true
image: Visual Studio 2022
test: false

install:
  # Appveyor uses git checkout -qf FETCH_HEAD but all GitVersion versions above 5.6.3 doesn't support this detached header
  # This is a workaround for this issue
  - ps: |
      if ($env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT -ne "")
      {
        git checkout -qf $($env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT)
      }
# - ps: Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1'
# - ps: ./dotnet-install.ps1 -Version 8.0.100 -InstallDir "C:\Program Files\dotnet"

pull_requests:
  do_not_increment_build_number: false

build_script:
  - ps: dotnet --info
  - ps: gitversion /version
  - ps: .\build.ps1 --target=ci --verbosity=diagnostic

after_build:
  - ps: gci -Filter *.trx -Path .\TestResults\ | % { (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_.FullName)) }

artifacts:
  - path: \Publish\*.*

nuget:
  disable_publish_on_pr: true

skip_commits:
  files:
    - '**/*.md'
